account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account import views

app_name = 'account'
urlpatterns = [
	path(r'login/', auth_views.login, name = 'login'),
	path(r'logout/', auth_views.logout, {'next_page':'/'}, name = 'logout'),
	path(r'signup/', views.signup, name = 'signup'), 
	


]

calendarproject/urls.py
from django.contrib import admin
from django.urls import reverse
from django.urls import path
from mainApp import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls', namespace='mainApp')),
    path('account/', include('account.urls', namespace='account')),

]

mainApp/urls.py
from django.urls import path
from mainApp import views

app_name = 'mainApp'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('calendar', views.calendar, name = 'calendar'),
	path('entry/<int:pk>', views.details, name = 'details' ),
	path('entry/add', views.add, name = 'add'),
	path('entry/delete/<int:pk>', views.delete, name = 'delete'),

]

account/models.py
from django.db import models

# Create your models here.

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Entry(models.Model):
	name = models.CharField(max_length = 100)
	author = models.ForeignKey(User, on_delete = models.CASCADE)
	date = models.DateTimeField()
	descriptions = models.TextField()
	created = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.name

mainApp/forms.py
from django import forms

class EntryForm(forms.Form):
	name = forms.CharField(max_length = 100)
	date = forms.DateTimeField()
	descriptions = forms.CharField(widget = forms.Textarea)

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password2']
			user = authenticate(username = username, password = password)
			login(request, user)
			return redirect('/calendar')
	else:
		form = UserCreationForm()
	return render(request, 'registration/signup.html', {'form':form})

mainApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Entry
from .forms import EntryForm

def index(request):
	return render(request, 'mainApp/index.html')

def calendar(request):
	entries = Entry.objects.filter(author = request.user)
	args = {'entries':entries}
	return render(request, 'mainApp/calendar.html', args)

def details(request, pk):
	entries = Entry.objects.get(id = pk)
	args = {'entries':entries}
	return render(request, 'mainApp/details.html', args)

def add(request):
	if request.method == 'POST':
		form = EntryForm(request.POST)
		if form.is_valid():
			name = form.cleaned_data['name']
			date = form.cleaned_data['date']
			descriptions = form.cleaned_data['descriptions']

			Entry.objects.create(
				name = name,
				author = request.user,
				date = date,
				descriptions = descriptions,
				).save()
			return HttpResponseRedirect('/calendar')
	else:
		form = EntryForm()
	return render(request, 'mainApp/add_form.html', {'form':form})


def delete(request, pk):
	if request.method == 'DELETE':
		entry = get_object_or_404(Entry, pk = pk)
		entry.delete()

	return HttpResponseRedirect('/')

mainApp/templates/mainApp/_calendar_entry.html
<div class="calendar_entry col-lg-4">
	<br />
	<h2>{{ entry.name }}</h2>
	<hr>
	<h4>{{ entry.date }}</h4>
	<p>
		{{ entry.descriptions|truncatechars:50 }}
	</p>
	<button onclick="window.location='{% url 'mainApp:details' pk=entry.id %}' " class="btn btn-primary">Details</button>
	<button data-id="{{ entry.id }}" onclick="deleteCalendarEntry(this)" class="btn btn-danger">Delete</button>

</div>

mainApp/templates/mainApp/add_form.html
{% extends 'mainApp/base.html' %}
{% load staticfiles %}

{% block base %}
<br>
	<h1>Add A New Event</h1>
	<form method="POST">
		{% for field in form %}
			{% csrf_token %}
			{{ field.errors }}
			<label>{{ field.label }}</label>
			<input placeholder="{{ field.label }}" name="{{ field.name }}" class="form-control">
		{% endfor %}
		<br>
		<button type="submit" class="btn btn-success">Submit</button>
	</form>
{% endblock %}

mainApp/templates/mainApp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Calendar</title>
	
	<link rel="stylesheet" type="text/css" href="{% static 'mainApp/bootstrap/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/main.css' %}">
	<script type="text/javascript" src="{% static 'mainApp/js/calendar.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript">
		var csrf_token = '{{ csrf_token }}'
	</script>
</head>
<body>
	<div class="container">
		{% block base %}
		{% endblock %}
	</div>

</body>
</html>

mainApp/templates/mainApp/calendar.html
{% extends 'mainApp/base.html' %}
{% load staticfiles %}

{% block base %}
<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<h1>Event Calendar</h1>
				{% if request.user.is_authenticated %}
					<span>Hi, {{ request.user.username }}</span>
					<a href="account/logout">Logout</a>
				{% endif %}
			</div>
			<div class="col-lg-4">
				<button onclick="window.location='entry/add'" type="button" class="btn btn-success">Add Event</button>
			</div>
		</div>
		<hr>
		<div class="row">
			{% for entry in entries %}
				{% include 'mainApp/_calendar_entry.html' %}
			{% endfor %}
		</div>
	</div>

{% endblock %}

mainApp/templates/mainApp/details.html
{% extends 'mainApp/base.html' %}
{% load staticfiles %}

{% block base %}

<div class="container jumbotron">
		<h1>{{ entries.name }}</h1>
		<span>{{ entries.date }}</span>
		<hr>
		<h3>{{ entries.descriptions }}</h3>
</div>


{% endblock %}

mainApp/templates/mainApp/index.html
{% extends 'mainApp/base.html' %}
{% load staticfiles %}

{% block base %}
<br>
	<div class="page-center container">
		<h1>Event Calendar</h1>
		<p>Add your event.</p>
		<button class="btn btn-success" onclick="window.location='account/login'">Login</button>
	</div>

{% endblock %}